### ISSUE TITLE
About port 5353

### ISSUE THREAD

**Issue by fananchong** [micro/mdns#18]
I have other app use mdns， like jenkins 、printer . 
so the following code will have problems :
```go
// Listen listens indefinitely for multicast updates
func Listen(entries chan<- *ServiceEntry, exit chan struct{}) error {
	// ...

	for {
		select {
		// ...
		case m := <-msgCh:
			// ...
			if e.complete() {
				// ...
			} else {
				// Fire off a node specific query
				m := new(dns.Msg)
				m.SetQuestion(e.Name, dns.TypePTR)
				// ...
			}
		}
	}

	return nil
}
```
`e.complete()` will return false, causing an infinite loop.

Please provide an initialization function that can specify port 5353 as the other.

**Comment by vtolstov** [comment]
why port 5353 does matter? mdns by default listens to 5353. code that you provide checks that we have service for this query with needed data. If you try to get services from micro mdns  that does not registered it can't answer on query and so return false.

**Comment by fananchong** [comment]
Port conflict, causing an infinite loop
