### ISSUE TITLE
use the server and client on the same host

### ISSUE THREAD

**Issue by vtolstov** [micro/mdns#9]
Hi. I'm in search of mdns package for service discovery. I'm try hashicorp/mdns and whyrusleeping/mdns.
My use case - each node runs mdns server that responds to queries and client to find needed node.
But in case of hashicorp/mdns and whyrusleeping/mdns i have  panic. But with you package - setsockopt: address already in use

So, how can i use this package for my use-case?

**Comment by asim** [comment]
Hi, sorry but unfortunately I don't have a good answer for you. We use this specifically for micro.
